@startuml

title __EXAMPLE_ABSTRACT_FACTORY's Class Diagram__\n

  namespace example_abstract_factory {
    interface example_abstract_factory.CarsFactory {
        {abstract} + createCoupe()
        {abstract} + createSedan()
    }
  }
  

  namespace example_abstract_factory {
    interface example_abstract_factory.Coupe {
        {abstract} + startRace()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.FordCoupe {
        + startRace()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.FordFactory {
        + createCoupe()
        + createSedan()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.FordSedan {
        + startRide()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.Main {
        {static} + getCarsFactory()
        {static} + main()
    }
  }
  

  namespace example_abstract_factory {
    interface example_abstract_factory.Sedan {
        {abstract} + startRide()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.ToyotaCoupe {
        + startRace()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.ToyotaFactory {
        + createCoupe()
        + createSedan()
    }
  }
  

  namespace example_abstract_factory {
    class example_abstract_factory.ToyotaSedan {
        + startRide()
    }
  }
  

  example_abstract_factory.FordCoupe .up.|> example_abstract_factory.Coupe
  example_abstract_factory.FordFactory .up.|> example_abstract_factory.CarsFactory
  example_abstract_factory.FordSedan .up.|> example_abstract_factory.Sedan
  example_abstract_factory.ToyotaCoupe .up.|> example_abstract_factory.Coupe
  example_abstract_factory.ToyotaFactory .up.|> example_abstract_factory.CarsFactory
  example_abstract_factory.ToyotaSedan .up.|> example_abstract_factory.Sedan


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
