@startuml

title __TASK_9's Class Diagram__\n

  namespace task_9 {
    interface task_9.Figure {
        {abstract} + fall()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_1 {
        + fall()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_1_Maker {
        + createFigure()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_2 {
        + fall()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_2_Maker {
        + createFigure()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_3 {
        + fall()
    }
  }
  

  namespace task_9 {
    class task_9.Figure_3_Maker {
        + createFigure()
    }
  }
  

  namespace task_9 {
    interface task_9.Figure_Maker {
        {abstract} + createFigure()
    }
  }
  

  namespace task_9 {
    class task_9.Main {
        {static} + getFigureByCountOfCells()
        {static} + main()
    }
  }
  

  namespace task_9 {
    class task_9.SuperFigure {
        - countOfCells : int
        + SuperFigure()
        + fall()
    }
  }
  

  namespace task_9 {
    class task_9.SuperFigure_Maker {
        - countOfCells : int
        + SuperFigure_Maker()
        + createFigure()
    }
  }
  

  task_9.Figure_1 .up.|> task_9.Figure
  task_9.Figure_1_Maker .up.|> task_9.Figure_Maker
  task_9.Figure_2 .up.|> task_9.Figure
  task_9.Figure_2_Maker .up.|> task_9.Figure_Maker
  task_9.Figure_3 .up.|> task_9.Figure
  task_9.Figure_3_Maker .up.|> task_9.Figure_Maker
  task_9.SuperFigure .up.|> task_9.Figure
  task_9.SuperFigure_Maker .up.|> task_9.Figure_Maker


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
